### ISSUE TITLE
Challenge 1: Add a patient summary screen 

### ISSUE THREAD

**Issue by dvidsilva** [awsm-eng/lotus-challenge#1]
We're using medplum for our FHIR storage, they also conveniently provide react components we can include in our codebase, and provide mock functions that make tests easier. 

For this challenge, create a patient summary screen in the `pages/patient` file. 

Use the `PatientSummary` component from [medplum](https://storybook.medplum.com/?path=/story/medplum-patientsummary--patient) 

Use the medplum mock client to display data when the page is loaded. [NPM](https://www.npmjs.com/package/@medplum/mock) 

Medplum has example repos and documentation you can use for reference:

[Chart demo](https://github.com/medplum/medplum-chart-demo)

[Patient Summary Stories](https://github.com/medplum/medplum/blob/main/packages/react/src/PatientSummary/PatientSummary.stories.tsx) 

[Medplum Storybook](https://storybook.medplum.com)

We're evaluating general knowledge of typescript, react, nextjs and github; and the general capacity to implement medplum in a codebase, since we rely heavily on that tool to leverage their FHIR storage. 

## Run locally 

`npm run dev` to open in `localhost:3000`

`npm run build` to verify lint and build work correctly 

`npm test-ci` to verify the tests are correct 

## Additional points

- Replace the test.todo with useful tests
- Use additional components from medplum to display other information about the patient in the screen
- Improve the styles of the page, with tailwind or mantine 

## Todo

- [ ] Make necesary changes 
- [ ] Create a pull request
- [ ] Verify that the github actions `test` and `build` execute correctly 
- [ ] If selected, meet with the team to discuss your approach
